name: Photography of Marco Martinez
favicon: null
layout_spectrum: 0.24769
typography_spectrum: 0.41179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06090e'
    - '#fdfdfd'
    - '#c6d4dd'
    - '#2d3539'
    - '#3d7ab1'
  brandStrength: 0.1875
  lightness: 0.9735603837762028
  saturation: 0.8576609739102423
  rhythmicContrast: 0.12371939746662974
purpose: []
